//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/_Scripts/Game/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""07b7e212-333e-42c1-bbe8-2215b99f6c1c"",
            ""actions"": [
                {
                    ""name"": ""Restart"",
                    ""type"": ""Value"",
                    ""id"": ""4d851efa-91f9-4425-b143-ca347a88da09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Record"",
                    ""type"": ""Button"",
                    ""id"": ""07047edc-42ce-4df1-9b85-d0237d6ab542"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""cf47c3fb-65ba-4fa2-8113-40e30b39975a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Load"",
                    ""type"": ""Button"",
                    ""id"": ""2acc504d-c310-4fad-bb73-f61b21029a3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""1493df94-8a16-417a-bec2-c71546fa6a48"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Replay"",
                    ""type"": ""Button"",
                    ""id"": ""e3806b8a-0635-4e84-a46b-c8e4e49b078b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heatmap"",
                    ""type"": ""Button"",
                    ""id"": ""7c86d8e3-e698-47a5-a829-8753d145e020"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Timer"",
                    ""type"": ""Button"",
                    ""id"": ""fb2e9053-3521-4881-ba0d-8a91150ec0d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""78ab909a-8d3b-46ca-98b2-d8b613c89806"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rewind"",
                    ""type"": ""Button"",
                    ""id"": ""4a0d8c15-41d9-4a0c-84f3-b6c79abff53c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastForward"",
                    ""type"": ""Button"",
                    ""id"": ""2a4025d6-6129-4675-8aaa-9256228d99a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e283861a-5a0b-4688-8288-55cb0d663e1c"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""567f65a5-b504-471a-912c-e49a447badef"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e67ed612-f800-4420-a5ad-0471247e043b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Record"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c42a649d-917a-42bf-a88f-3215fa91c670"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a87186d6-3d79-442d-9e16-2b9af54dd53d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71caf2b7-a96b-4e2c-a287-7a4b115bd085"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Load"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""670f4e2a-2bf3-4fa8-ba3c-9ee9bee243e9"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Load"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed84300f-451a-44df-9373-a7a0eb55e31c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b08b10b5-4eb5-49c8-b1a7-78c03a3890d3"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78c7db5e-bc3c-4f41-8a1a-ad113c1bb923"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Replay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1db18824-939d-4757-80ec-579ffaa80461"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Replay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cd01ff1-42b2-4497-a44d-f00769486b7a"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heatmap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4079c7c2-31ca-48cc-b706-6f56fde97b78"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Timer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf00be07-c4fa-4302-8762-070109d348ed"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a789ad1-2393-4d04-a23f-145ff87d8d7a"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rewind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e666c524-38c7-493d-9916-d441e3ac6af3"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_Restart = m_Game.FindAction("Restart", throwIfNotFound: true);
        m_Game_Record = m_Game.FindAction("Record", throwIfNotFound: true);
        m_Game_Stop = m_Game.FindAction("Stop", throwIfNotFound: true);
        m_Game_Load = m_Game.FindAction("Load", throwIfNotFound: true);
        m_Game_Save = m_Game.FindAction("Save", throwIfNotFound: true);
        m_Game_Replay = m_Game.FindAction("Replay", throwIfNotFound: true);
        m_Game_Heatmap = m_Game.FindAction("Heatmap", throwIfNotFound: true);
        m_Game_Timer = m_Game.FindAction("Timer", throwIfNotFound: true);
        m_Game_Menu = m_Game.FindAction("Menu", throwIfNotFound: true);
        m_Game_Rewind = m_Game.FindAction("Rewind", throwIfNotFound: true);
        m_Game_FastForward = m_Game.FindAction("FastForward", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private IGameActions m_GameActionsCallbackInterface;
    private readonly InputAction m_Game_Restart;
    private readonly InputAction m_Game_Record;
    private readonly InputAction m_Game_Stop;
    private readonly InputAction m_Game_Load;
    private readonly InputAction m_Game_Save;
    private readonly InputAction m_Game_Replay;
    private readonly InputAction m_Game_Heatmap;
    private readonly InputAction m_Game_Timer;
    private readonly InputAction m_Game_Menu;
    private readonly InputAction m_Game_Rewind;
    private readonly InputAction m_Game_FastForward;
    public struct GameActions
    {
        private @GameControls m_Wrapper;
        public GameActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Restart => m_Wrapper.m_Game_Restart;
        public InputAction @Record => m_Wrapper.m_Game_Record;
        public InputAction @Stop => m_Wrapper.m_Game_Stop;
        public InputAction @Load => m_Wrapper.m_Game_Load;
        public InputAction @Save => m_Wrapper.m_Game_Save;
        public InputAction @Replay => m_Wrapper.m_Game_Replay;
        public InputAction @Heatmap => m_Wrapper.m_Game_Heatmap;
        public InputAction @Timer => m_Wrapper.m_Game_Timer;
        public InputAction @Menu => m_Wrapper.m_Game_Menu;
        public InputAction @Rewind => m_Wrapper.m_Game_Rewind;
        public InputAction @FastForward => m_Wrapper.m_Game_FastForward;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void SetCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterface != null)
            {
                @Restart.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRestart;
                @Restart.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRestart;
                @Restart.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRestart;
                @Record.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRecord;
                @Record.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRecord;
                @Record.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRecord;
                @Stop.started -= m_Wrapper.m_GameActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnStop;
                @Load.started -= m_Wrapper.m_GameActionsCallbackInterface.OnLoad;
                @Load.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnLoad;
                @Load.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnLoad;
                @Save.started -= m_Wrapper.m_GameActionsCallbackInterface.OnSave;
                @Save.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnSave;
                @Save.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnSave;
                @Replay.started -= m_Wrapper.m_GameActionsCallbackInterface.OnReplay;
                @Replay.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnReplay;
                @Replay.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnReplay;
                @Heatmap.started -= m_Wrapper.m_GameActionsCallbackInterface.OnHeatmap;
                @Heatmap.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnHeatmap;
                @Heatmap.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnHeatmap;
                @Timer.started -= m_Wrapper.m_GameActionsCallbackInterface.OnTimer;
                @Timer.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnTimer;
                @Timer.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnTimer;
                @Menu.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMenu;
                @Rewind.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRewind;
                @Rewind.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRewind;
                @Rewind.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRewind;
                @FastForward.started -= m_Wrapper.m_GameActionsCallbackInterface.OnFastForward;
                @FastForward.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnFastForward;
                @FastForward.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnFastForward;
            }
            m_Wrapper.m_GameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Restart.started += instance.OnRestart;
                @Restart.performed += instance.OnRestart;
                @Restart.canceled += instance.OnRestart;
                @Record.started += instance.OnRecord;
                @Record.performed += instance.OnRecord;
                @Record.canceled += instance.OnRecord;
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
                @Load.started += instance.OnLoad;
                @Load.performed += instance.OnLoad;
                @Load.canceled += instance.OnLoad;
                @Save.started += instance.OnSave;
                @Save.performed += instance.OnSave;
                @Save.canceled += instance.OnSave;
                @Replay.started += instance.OnReplay;
                @Replay.performed += instance.OnReplay;
                @Replay.canceled += instance.OnReplay;
                @Heatmap.started += instance.OnHeatmap;
                @Heatmap.performed += instance.OnHeatmap;
                @Heatmap.canceled += instance.OnHeatmap;
                @Timer.started += instance.OnTimer;
                @Timer.performed += instance.OnTimer;
                @Timer.canceled += instance.OnTimer;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @Rewind.started += instance.OnRewind;
                @Rewind.performed += instance.OnRewind;
                @Rewind.canceled += instance.OnRewind;
                @FastForward.started += instance.OnFastForward;
                @FastForward.performed += instance.OnFastForward;
                @FastForward.canceled += instance.OnFastForward;
            }
        }
    }
    public GameActions @Game => new GameActions(this);
    public interface IGameActions
    {
        void OnRestart(InputAction.CallbackContext context);
        void OnRecord(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
        void OnLoad(InputAction.CallbackContext context);
        void OnSave(InputAction.CallbackContext context);
        void OnReplay(InputAction.CallbackContext context);
        void OnHeatmap(InputAction.CallbackContext context);
        void OnTimer(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnRewind(InputAction.CallbackContext context);
        void OnFastForward(InputAction.CallbackContext context);
    }
}
